### PR TITLE
creation of Archived section for historical versions eg v0

### PR DESCRIPTION
**Pull request by ross-spencer**
Just opening this up for discussion @Christian-MK

### CODE REVIEW

**Comment by ross-spencer** [comment]
* Do we want to roll with archive? It is often a loaded term. 
* My vote would be to not have the IOG part here. 
* One of the more important parts of the history/archive is to list previous policy IDs. Maybe we can also have another page that lists these? Example structure:

```
# orcfax policies

Historical oracle policies are listed here. 

## current

* mainnet
* preprod

## legacy

### v0 

V0 uses a legacy datum format, see "archived resources" for how to interpret the data previously put on-chian.

* mainnet
* preprod

## v1

* etc.
* etc.

**Comment by Christian-MK** [comment]
> * Do we want to roll with archive? It is often a loaded term.

Not married to anything, suggestions?

> * One of the more important parts of the history/archive is to list previous policy IDs. Maybe we can also have another page that lists these? Example structure:

other policy ID's than are listed on this page?
Preprod: https://github.com/orcfax/docs/blob/Archived-section/docs/developer-manual/archived.md#preprod
Mainnet: https://github.com/orcfax/docs/blob/Archived-section/docs/developer-manual/archived.md#mainnet

Or is it that you wish to have these stand alone, away from any context or other resources shared relating to historical versions?

**Comment by Christian-MK** [comment]
> * Example structure:

Fine with this structure but want clarity on the previous question re the other content (eg context)

**Comment by ross-spencer** [comment]
> Or is it that you wish to have these stand alone, away from any context or other resources shared relating to historical versions?

Yes please! For those reasons, just free from the additional documentation that existed. The current page is fine as is too, that is, more like you say, like an archive, I used the term archived resources above.

> Archive vs. anything else?

For the policies, maybe "Legacy policies and addresses" with the minimal context provided in the example?

**Comment by Christian-MK** [comment]
What an ugly commit history.. apologies. Evidence of me still learning how to efficiently use git.

@ross-spencer I have implemented your suggestion to trim down the policies page just to the bare minimum while creating a separate page for context and links.

**Review by ross-spencer — COMMENTED** [review]
Looks good to me. Info about slots/blockheader here: https://github.com/orcfax/issues/issues/166#issuecomment-2191199360 just needs adding then merging.

LMK if you ever want to learn to rebase (to clean up commit histories)

NB. apparently I can't "approve" :shrug:

**Pull request merged**
