### PR TITLE
m1 deliverables for explorer

### PR DESCRIPTION
**Pull request by Christian-MK**
# Explorer M1 deliverables

a section of the docs where we link out to the deliverables promised. While this is not a direct match to what I will submit to catalyst, it will share much of the same information.

## catalyst PoA

The following is what I would like to submit to Catalyst: 

**What we promised:**
Orcfax will develop a dashboard page on the Orcfax Explorer that utilizes highly informative visualizations to aid users. These new visualizations may include (but are not limited to):
* Orcfax feed price charts (eg ADA-USD)
* state change timelines (eg the life cycle of data)
* data provenance (eg methods for verifying authenticity)
The following will be posted on the public Orcfax GitHub:
* Source code
* test case documentation with results

**What we delivered:**
4 new Orcfax Explorer features!
1. Show validation details on UI: https://github.com/orcfax/explorer.orcfax.io/issues/5
	This information gives users an enhanced ability to to verify the authenticity of the collected data by visualizing the validation steps taken on the data received by our collector nodes.
1. Show calculation details on UI: https://github.com/orcfax/explorer.orcfax.io/issues/4
	This information explains how data is aggregated and what calculations are executed over that data which results in the on-chain value.
1. Show collection details on UI: https://github.com/orcfax/explorer.orcfax.io/issues/3
	This information allows users to trace where data is being pulled from and from which entities as feeds are constructed. This gives users an unrivaled ability to check the provenance of the data.
1. Display sources: https://github.com/orcfax/explorer.orcfax.io/issues/2

For test cases, we have recorded a walkthrough of explorer.orcfax.io so that users can see how the new features work in tandem to deliver an incredible explorer experience. This walkthrough also serves as a resource for users looking to better understand the upgrades within the context of the explorer UI.

What’s more, our team has been able to make this progress ahead of the first f12 funding disbursement which took place the beginning of October 2024; this diligence means that our team has been able to stay on track with our proposed timeline despite administrative delays!

## Outstanding Questions

* A required feature is “price feed charts” but these are not listed in the issues; Is there a commit that has transpired during m1 that I can point to and then add this feature to the list?
* Completed issues are not tied to any commits so I don’t have an easy way of directing reviewers to the code which has been upgraded or the ability to articulate where in the code these updates exist (need for “source code”)

### CODE REVIEW

**Comment by gchartier** [comment]
I added and immediately closed 3 historical issues from the old explorer repo to the new open-source explorer repo. They are also linked to milestone 1 totaling 7 issues for milestone 1.

You can see them all here:
https://github.com/orcfax/explorer.orcfax.io/milestone/1?closed=1

Also added a comment to each issue with a link to code files to verify what was done.

**Comment by gchartier** [comment]
Couple other things to note:

For the 4 issues listed above in this PR, I linked to the actual PR containing just the commits relevant to those 4 features which should make reviewing/verifying very easy.

However, for the other 3 issues related to feeds, the commit I linked to is the first one in this public explorer repo because the work was done when the explorer was closed-source. When we open-sourced the explorer, we pruned the git commit history for security reasons as there were some IP addresses and urls in the git commit history and we wanted to start from a clean slate. So while these features are 100% verifiable via the linked commit, there's more code to dig through.

Last, there are a lot more features than just 4. The number of features is not necessarily 1:1 with the number of issues. Some issues have lots of features in them and some are just a single feature.

Let me know how else I can help in making this easier to communicate!

**Comment by Christian-MK** [comment]
@gchartier 
> Let me know how else I can help in making this easier to communicate!

Just reworked and tried to align the 1..m relationship of what was promised to what we are delivering. Let me know what you think and approve when ready

**Review by gchartier — APPROVED** [review]
Just fixed some minor capitalization and duplicate words. LGTM!

**Pull request merged**
