### PR TITLE
Add Phase 1 Technical information

### PR DESCRIPTION
**Pull request by ross-spencer**

### CODE REVIEW

**Review by Christian-MK — APPROVED** [review]
Made some minor stylistic changes and grammatical stuff. Looks great!

**Comment by ross-spencer** [comment]
Thanks for this @Christian-MK. Before merging I just added the aliasing docs and updated the TODO in the phase-1 page. Can you take a look at this new page as well?

**Review by Christian-MK — APPROVED** [review]
looks great!

**Comment by ross-spencer** [comment]
NB. clearer cli docs added: https://github.com/orcfax/docs/pull/47/commits/c30a29790c256513550ffc0ebf7349dfcbc91563

**Comment by gchartier** [comment]
I shipped the new docs site and rebased this branch fyi.

**Comment by ross-spencer** [comment]
> How do we feel about using [admonitions](https://docusaurus.io/docs/markdown-features/admonitions) for callout blocks like those that use NB.?

looks great!! this is something I wanted to tap into with the quotes, i didn't know this technique!

**Comment by gchartier** [comment]
My final edits / suggestions are submitted. Let me know what you think.

**Comment by gchartier** [comment]
My additions might seem like overkill, but it was all the roadblocks and info I needed to make it work when I did the dry run.

**Comment by ross-spencer** [comment]
> My additions might seem like overkill, but it was all the roadblocks and info I needed to make it work when I did the dry run.

Not at all! Thanks for the extra eyes and the helpful additions, all merged and ready to go!

**Pull request merged**
