### PR TITLE
lists feeds per Peters request

### PR DESCRIPTION
**Pull request by Christian-MK**
combines all currently available feeds into a single table for ease of reference.

### CODE REVIEW

**Comment by ross-spencer** [comment]
I don't know where this has come from? Do we have an existing issue for this that describes what is desired? Is there some fire under this I am not aware of that means we're ignoring process?

This is really unmaintainable, plus, I don't know where the data is coming from, we have some UUIDs (?) describing a feed? But this is simply an implementation detail in the Explorer -- it exists no where else in the stack.

We have: https://github.com/orcfax/cer-feeds/blob/main/feeds/cer-feeds.json for a reason and we can reference that, otherwise we have an Explorer we can link out to -- this is the only link we need.

**Comment by Christian-MK** [comment]
> Is there some fire under this I am not aware of that means we're ignoring process?

Peter asked for a list of all currently available feeds be made so that he might reference/share a link to it during his upcoming interviews.

**Comment by ross-spencer** [comment]
> I could write something like, "A list of all currently available CER feeds can be found here" 

If we did this then it would create more space to describe the feed definitions:

> subsidized 
> Orcfax will pay these for a certain time and we will let everyone know in advance > before removing the subsidy.

> showcase 
> These are just to showcase our oracle's capabilities and a way for projects to test > them out on mainnet. They can be removed/changed at any moment.

And then, to see subsidized/showcased feeds, please take a look at: <cer-feeds.json>

NB. we can also create a small HTML from cer-feeds.json and publish it to a github pages, very easily, that might be a good approach here (see glossary for previous form)

**Comment by peterVG** [comment]
we currently don't have a list view on our explorer that gives an easy overview of what total number of feeds we actually do provide
we also don't such a list anywhere in our docs

**Review by peterVG — COMMENTED** [review]
Unitl we have a list view on the Explorer we currently don't have a simple single overview of all the feeds offerecd on mainnet. I appreciate that this is a static, manual list but I need to be able to point to somehithing.

**Comment by ross-spencer** [comment]
> we currently don't have a simple single overview of all the feeds offerecd on mainnet

image

**Pull request merged**
