### PR TITLE
economic model content from Vahid's monetization doc

### PR DESCRIPTION
**Pull request by Christian-MK**
I was tasked with updating the economic model given some of the decisions made by the business team.
I have pulled details from the Business Model google doc [here](https://docs.google.com/document/d/14R9zCVn6wsFLbHV1SslFo5LzLJcp2h1Az446_vM7K3g/edit?pli=1)

### CODE REVIEW

**Comment by Christian-MK** [comment]
@ross-spencer could you enable equations in docusaurus? I read through the [documentation](https://docusaurus.io/docs/markdown-features/math-equations) and see that [KaTeX](https://katex.org/) is suggested, but its using docusaurus v3. Any suggestions?

**Comment by ross-spencer** [comment]
@Christian-MK wanna give this branch a whirl to see if you can render it as you'd like?

https://github.com/orcfax/docs/pull/22

**Comment by Christian-MK** [comment]
> @Christian-MK wanna give this branch a whirl to see if you can render it as you'd like?
> 
> #22

Ack! Sorry I never replied, this works well for my limited use case, cheers

**Comment by Christian-MK** [comment]
This branch is waiting for the final review of the underlying doc by both vahid and Xerberus

**Pull request closed without merging**
