### PR TITLE
addition of catalyst section w/ proposals

### PR DESCRIPTION
**Pull request by Christian-MK**
Orcfax is obligated to make catalyst deliverables accessible to the public. This section of the docs is meant to create a space where we can meet this obligation

### CODE REVIEW

**Comment by Christian-MK** [comment]
@ross-spencer any insight into how I can get Mermaid to render in docusaurus?
I tried adding 
```
export default {
  markdown: {
    mermaid: true,
  },
  themes: ['@docusaurus/theme-mermaid'],
};
```
to docusaurus.config.js but couldn't get it to work. Some searching online didnt turn up any useful guides for me, but I'm sure I'm missing something simple.

**Comment by ross-spencer** [comment]
@Christian-MK at least today, I seem to be falling short on this one -- I wonder if @gchartier can provide some ideas. 

Basically, on top of what you've done, I think you need to add mermaid via npm, e.g.

```sh
$ npm install --save @docusaurus/theme-mermaid
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: client@0.0.0
npm error Found: react@17.0.2
npm error node_modules/react
npm error   react@"^17.0.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^18.0.0" from @docusaurus/theme-mermaid@3.5.2
npm error node_modules/@docusaurus/theme-mermaid
npm error   @docusaurus/theme-mermaid@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/ross-spencer/.npm/_logs/2024-09-04T12_46_10_987Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/ross-spencer/.npm/_logs/2024-09-04T12_46_10_987Z-debug-0.log
```

But as you can see there are errors and I think we maybe need to install pinned to a previous version but I'm not having a lot of luck with the commands there. 

Any ideas @gchartier

**Comment by gchartier** [comment]
Looked into this and was able to bypass the warnings by running `npm install @docusaurus/theme-mermaid --legacy-peer-deps` but tbh this is a bandaid.

We should probably update docusaurus because it's running an unmaintained old version which is why there's all kinds of peer dependency errors.

**Comment by Christian-MK** [comment]
> Looked into this and was able to bypass the warnings by running `npm install @docusaurus/theme-mermaid --legacy-peer-deps` but tbh this is a bandaid.

even with this I'm still not seeing the rendered mermaid when running `npm start`

Per you comment this seems like something that will not be fixed owing to priority. I'm going to remove the mermaid for now and circle back in a separate PR

**Comment by gchartier** [comment]
Yeah @Christian-MK it still won't run because it needs to be wired up in the config plugins/themes based on my reading of the docs, but unfortunately all of the docs have the newer version of the config and I can't find a way to make it work in this version of docusaurus

**Comment by ross-spencer** [comment]
Added this info to here: https://github.com/orcfax/issues/issues/121 

We should try and address this soon after mainnet launch.

**Pull request merged**
